version: "3.8"

x-shared-env: &env
  LEADER: ra@node0.dsmt
  # erlnag -name is name@host
  NODE_NAME_NAME: ra


services:
  node0:
    build: .
    hostname: node0.dsmt
    environment:
      <<: *env
    ports:
      - 127.0.0.1:8080:8080
    # volumes:
    #   - node0_data:/data

  node1:
    build: .
    hostname: node1.dsmt
    environment:
      <<: *env
    ports:
      - 127.0.0.1:8081:8080
    # volumes:
    #   - node1_data:/data
    depends_on:
      - node0

  node2:
    build: .
    hostname: node2.dsmt
    environment:
      <<: *env
    ports:
      - 127.0.0.1:8082:8080
    # volumes:
    #   - node2_data:/data
    depends_on:
      - node0

# volumes:
#   node0_data:
#   node1_data:
#   node2_data: